### ISSUE TITLE
no devices found

### ISSUE THREAD

**Issue by gklank** [AShifter/EcpEmuServer#1]
Hi,

got it installed on a Ubuntu 22.04 machine, see below the following output:
[i] info @ 7/12/2022 10:59:34 PM: EcpEmuServer started (press CTRL+C twice to terminate)
[i] info @ 7/12/2022 10:59:34 PM: RuleManager running, loading rules...
[*] success @ 7/12/2022 10:59:34 PM: Loaded rule "Beide Lampen" from rules.xml for button "Home"
[i] info @ 7/12/2022 10:59:34 PM: Button API running
[!] warn @ 7/12/2022 10:59:34 PM: SSDP Multicasting with address 127.0.1.1 (if this is not your preferred interface, try disabling others)

I can access the EcpEmuServer with IP:8060 and getting the following answer:
<root>
<device>
<friendlyName>EcpEmuServer</friendlyName>
<manufacturer>Roku</manufacturer>
<manufacturerURL>http://www.github.com/ashifter/EcpEmuServer</manufacturerURL>
<modelName>Streaming Stick+</modelName>
<serialNumber>jammy-1</serialNumber>
<UDN>uuid:jammy-1</UDN>
</device>
</root>

I used the the following input within the myharmony app:
Roku
Streaming +

And secondly:
Roku
Harmony Span

But the myharmony App from Logitech is telling that no devices were found.

Any further help would be appreciated.

Regards

Gerhard

**Comment by gklank** [comment]
Hi,

version 0.2.2 is functioning thanks!!!

Regards,


Gerhard

**Comment by AShifter** [comment]
Hello Gerhard,

Yep I was facing this same issue when I was testing the app on different computers earlier and released v0.2.2 to fix that - I'm glad to hear it's working now!

Feel free to open another issue if you have any trouble with the app or you have a suggestion that could help improve it.

Thanks again,

Logan
