### ISSUE TITLE
The directory name is invalid.

### ISSUE THREAD

**Issue by miketheman986** [AShifter/EcpEmuServer#3]
I'm trying to run a python script from the end point and I get the following error:
'An error occurred trying to start process 'BobOff.py' with working directory 'C:\EcpEmuServer-win_x64\BobOff.py'. The directory name is invalid.'

Even trying your example of calling cmd.exe gives me the same error:
 'An error occurred trying to start process 'C:\Windows\System32\cmd.exe' with working directory 'C:\Windows\System32\cmd.exe'. The directory name is invalid.'

It looks like it is trying to pass the file name as part of the path?  

Here is my rules.xml for reference:
<rules>
    <rule>
      <Name>Bob Test On</Name>
      <Button>Up</Button>
      <Action>Execute</Action>
      <EndPoint>C:\Windows\System32\cmd.exe</EndPoint>
      <ExData> </ExData>
    </rule>
    <rule>
      <Name>Bob Test Off</Name>
      <Button>Down</Button>
      <Action>Execute</Action>
      <EndPoint>BobOff.py</EndPoint>
      <ExData> </ExData>
    </rule>

Also, you mentioned the possibility of being able to bind a different IP address?  This would be very helpful for me.  I run a VPN on the same server I'm running EcpEmuServer and I need to be able to bind to the local IP, not the VPN IP (I hope that makes sense?).

PS  This is a great program.  Once I get these issues sorted, it is exactly what I need.  Thanks so much!

**Comment by miketheman986** [comment]
Hi, just wondering if you've had a chance to look at this, or if its simply something I'm doing wrong?

Thanks!

**Comment by AShifter** [comment]
Hi there, apologies for the big delay - I will look into this one, I didn't have this on my machine.

I will also see how I can implement the ability to bind to other IP addresses, would probably solve a lot of headache!

**Comment by miketheman986** [comment]
Great, thanks for taking a look.  Let me know if you need any details or if you need me to test anything.

**Comment by miketheman986** [comment]
Any chance you've had some time to look at this yet?

**Comment by AShifter** [comment]
Hey Mike, sorry I haven't looked at this in such a long time, life gets in the way :)
I have drafted up a new release https://github.com/AShifter/EcpEmuServer/releases/tag/v0.2.3 which should have fixed the working directory issue. I'll be experimenting with a way to manually provide an IP to bind to. Apologies again for the wait.

**Comment by miketheman986** [comment]
Not a problem, I totally understand.  I appreciate you getting it fixed up.  I look forward to doing some testing.

**Comment by miketheman986** [comment]
This is working perfectly now.  Really great program!  I'm finally able to control my TP Link switches with my Harmony remote!

**Comment by AShifter** [comment]
Glad to hear it, feel free to open another issue if you run into any other issues. I scrolled through this one again and noticed you mentioned wanting to be able to bind to a different IP than the auto-discovered one so I will work on that sooner or later as well. Have fun!
