### ISSUE TITLE
Not creating the Roku device

### ISSUE THREAD

**Issue by Tcoble3** [AShifter/EcpEmuServer#4]
I've successfully used EcpEmuServer for several months, but recently lost functionality. I'm attempting to re-install everything and start from scratch (except for re-using the original Rules file). However, this time around the virtual Roku device isn't being created. I'm not getting any error messages - it's just not there to add to my Harmony activities. Would appreciate any guidance in troubleshooting. Thx!

**Comment by tcoble33** [comment]
Scratch that. I'm not sure what I did (if anything) to resolve this issue, but the virtual Roku device was eventually created. I believe it was a recent Windows update that triggered the problem, and that updating some of the various Core Runtime files may have helped solve the problem.

**Comment by AShifter** [comment]
Good to hear! sorry about the delay, but yeah sometimes you'll just get weird updates or network issues that keep it from working the first time. Will close the issue for now.
